export const START_LOADING = "START_LOADING";
export const FINISH_LOADING = "FINISH_LOADING";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const SET_QUERIES = "SET_QUERIES";
export const FETCHING_STARTED = "FETCHING_STARTED";
export const CHANGE_SEARCH_INPUT = "CHANGE_SEARCH_INPUT";
export const UPDATE_RESULTS_DATA = "UPDATE_RESULTS_DATA";
export const CLEAR_SEARCH_TERM = "CLEAR_SEARCH_TERM";
export const SET_USERS = "SET_USERS";
export const SET_USER = "SET_USER";


